TRAIN_DATA_PATH :  './data/dataset/LT_with_noise/food_LT_0.01/'
TEST_DATA_PATH  :  './data/dataset/Food-101N/val/'
RESAMPLE_PATH   :  './noise_longtail/code/ClassAwareSampler.py'
CHECKPOINT_PATH      :  './noise_longtail/model/food_101N/checkpoint/'
CLASSIFER_PATH       :  './noise_longtail/model/food_101N/classifer/'
PTH_STAGE_1_PATH     :   './noise_longtail/model/food_101N/checkpoint/checkpoint_best.pth.tar'
PTH_STAGE_2_PATH     :   './noise_longtail/model/food_101N/classifer/checkpoint_best.pth.tar'
JSON_PATH            : './noise_longtail/json/food_101N/score_dict.json'
FIANL_WEIGHT_PATH    :  './noise_longtail/json/food_101N/final_dict.json'
FINAL_MODEL_PATH     :  './noise_longtail/model/food_101N/best_model/'





#iterative learning
ITER_CHECKPOINT_PATH      :  './noise_longtail/iterative_model/food_101N/checkpoint/'
ITER_CLASSIFER_PATH       :  './noise_longtail/iterative_model/food_101N/classifer/'
ITER_PTH_STAGE_1_PATH     :   './noise_longtail/iterative_model/food_101N/checkpoint/checkpoint_best.pth.tar'
ITER_PTH_STAGE_2_PATH     :   './noise_longtail/iterative_model/food_101N/classifer/checkpoint_best.pth.tar'
ITER_JSON_PATH            : './noise_longtail/iterative_json/food_101N/score_dict.json'
ITER_FIANL_WEIGHT_PATH    :  './noise_longtail/iterative_json/food_101N/final_dict.json'
ITER_FINAL_MODEL_PATH     :  './noise_longtail/iterative_model/food_101N/best_model/'




batch_size      : 512
cls_num         : 101
logit_adjust    : 0
resample        : 0
mix_up          : 0
mix_up_weight   : 1
