TRAIN_DATA_PATH :  './data/dataset/LT_with_noise/LT_noise/red_noise_nl_0.3'
TEST_DATA_PATH  :  './data/dataset/mini-imagenet/validation/'
RESAMPLE_PATH   :  './noise_longtail/code/ClassAwareSampler.py'
CHECKPOINT_PATH      :  './noise_longtail/model/imagenet/red/checkpoint/0.3'
CLASSIFER_PATH       :  './noise_longtail/model/imagenet/red/classifer/0.3'
PTH_STAGE_1_PATH     :   './noise_longtail/model/imagenet/red/checkpoint/0.3/checkpoint_best.pth.tar'
PTH_STAGE_2_PATH     :   './noise_longtail/model/imagenet/red/classifer/0.3/checkpoint_best.pth.tar'
JSON_PATH            : './noise_longtail/json/imagenet/red/0.3/0.3_score_dict.json'
FIANL_WEIGHT_PATH    :  './noise_longtail/json/imagenet/red/0.3/0.3_final_dict.json'
FINAL_MODEL_PATH     :  './noise_longtail/model/imagenet/red/best_model/0.3'



#iterative learning
ITER_CHECKPOINT_PATH      :  './noise_longtail/iterative_model/imagenet/red/checkpoint/0.3'
ITER_CLASSIFER_PATH       :  './noise_longtail/iterative_model/imagenet/red/classifer/0.3'
ITER_PTH_STAGE_1_PATH     :   './noise_longtail/iterative_model/imagenet/red/checkpoint/0.3/checkpoint_best.pth.tar'
ITER_PTH_STAGE_2_PATH     :   './noise_longtail/iterative_model/imagenet/red/classifer/0.3/checkpoint_best.pth.tar'
ITER_JSON_PATH            : './noise_longtail/iterative_json/imagenet/red/0.3/0.3_score_dict.json'
ITER_FIANL_WEIGHT_PATH    :  './noise_longtail/iterative_json/imagenet/red/0.3/0.3_final_dict.json'
ITER_FINAL_MODEL_PATH     :  './noise_longtail/iterative_model/imagenet/red/best_model/0.3'


batch_size      : 512
cls_num         : 100
logit_adjust    : 0
resample        : 0
mix_up          : 1
mix_up_weight   : 0